apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  type: NodePort
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management-console
  - port: 5672
    targetPort: 5672
    protocol: TCP 
    name: rabbit-port
  selector:
    app: rabbitmq