apiVersion: v1
kind: Service
metadata:
  name: comsumer-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: comsumer-service
  selector:
    app: consumer-service