version: '2'

services:

   rabbit:

       image: rabbitmq:3-management

       ports:

           - "5672:5672"

           - "15672:15672"

   postgres:

       image: postgres

       restart: always

       ports:

           - "5432:5432"

       environment:

           - POSTGRES_PASSWORD=admin

           - POSTGRES_USER=admin

           - POSTGRES_DB=postgres

   publisher:

       build: ./producer-service

       image: producer-service

       environment:

            - RABBITMQ_HOST=amqp://rabbit

   consumer:

       build: ./consumer-service

       image: consumer-service

       ports:

           - "8000:8000"

       environment:

           - POSTGRES_HOST=postgres

           - POSTGRES_PASSWORD=admin

           - POSTGRES_USER=admin

           - POSTGRES_DB=postgres

           - RABBITMQ_HOST=amqp://rabbit


